name: Build for pushes and PR

on:
  push:
    branches: [ "feat/pinedebug" ]
  pull_request:
    branches: [ "feat/pinedebug" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 5.0
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v6.0.0
      with:
        name: BBPC.dll
        path: ./BBPC/Build/Debug/BBPC.dll
